-- MySQL Script generated by MySQL Workbench
-- Fri Apr 29 10:27:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrera` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `car_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`car_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `tip_id` INT NOT NULL AUTO_INCREMENT,
  `tip_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`tip_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nivel` (
  `niv_id` INT NOT NULL AUTO_INCREMENT,
  `niv_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`niv_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recurso` (
  `rec_id` INT NOT NULL AUTO_INCREMENT,
  `rec_nombre` VARCHAR(60) NULL,
  `rec_resumen` TEXT NULL,
  `rec_fktipo` INT NULL,
  `rec_fknivel` INT NULL,
  PRIMARY KEY (`rec_id`),
  INDEX `recursostipo_idx` (`rec_fktipo` ASC) VISIBLE,
  INDEX `recursosniveles_idx` (`rec_fknivel` ASC) VISIBLE,
  CONSTRAINT `recursostipo`
    FOREIGN KEY (`rec_fktipo`)
    REFERENCES `mydb`.`tipo` (`tip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recursosniveles`
    FOREIGN KEY (`rec_fknivel`)
    REFERENCES `mydb`.`nivel` (`niv_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`palabra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`palabra` (
  `pal_id` INT NOT NULL AUTO_INCREMENT,
  `pal_nombre` VARCHAR(30) NULL,
  `pal_fkrecurso` INT NULL,
  PRIMARY KEY (`pal_id`),
  INDEX `recurso_idx` (`pal_fkrecurso` ASC) VISIBLE,
  CONSTRAINT `recurso`
    FOREIGN KEY (`pal_fkrecurso`)
    REFERENCES `mydb`.`recurso` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Keyword`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Keyword` (
  `key_id` INT NOT NULL,
  `key_name` VARCHAR(30) NULL,
  PRIMARY KEY (`key_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archivo` (
  `arc_id` INT NOT NULL AUTO_INCREMENT,
  `arc_nombre` VARCHAR(50) NULL,
  `arc_extencion` VARCHAR(5) NULL,
  `arc_nombrerOri` VARCHAR(50) NULL,
  `arc_vistas` INT NULL,
  `arc_descargas` INT NULL,
  `arc_mimetype` TEXT NULL,
  PRIMARY KEY (`arc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recurso_archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recurso_archivo` (
  `reca_id` INT NOT NULL AUTO_INCREMENT,
  `reca_fkarchivo` INT NULL,
  `reca_fkrecursos` INT NULL,
  PRIMARY KEY (`reca_id`),
  INDEX `resource_idx` (`reca_fkrecursos` ASC) VISIBLE,
  INDEX `file_idx` (`reca_fkarchivo` ASC) VISIBLE,
  CONSTRAINT `resource`
    FOREIGN KEY (`reca_fkrecursos`)
    REFERENCES `mydb`.`recurso` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `file`
    FOREIGN KEY (`reca_fkarchivo`)
    REFERENCES `mydb`.`archivo` (`arc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recurso_carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recurso_carrera` (
  `recc_id` INT NOT NULL AUTO_INCREMENT,
  `recc_fkrecurso` INT NULL,
  `recc_fkcarrera` INT NULL,
  PRIMARY KEY (`recc_id`),
  INDEX `career_idx` (`recc_fkcarrera` ASC) VISIBLE,
  INDEX `resource_idx` (`recc_fkrecurso` ASC) VISIBLE,
  CONSTRAINT `career`
    FOREIGN KEY (`recc_fkcarrera`)
    REFERENCES `mydb`.`carrera` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `resource`
    FOREIGN KEY (`recc_fkrecurso`)
    REFERENCES `mydb`.`recurso` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor_tipo` (
  `autt_id` INT NOT NULL,
  `autt_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`autt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `dep_id` INT NOT NULL AUTO_INCREMENT,
  `dep_nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`dep_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`encargado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`encargado` (
  `enc_id` INT NOT NULL AUTO_INCREMENT,
  `enc_nombre` VARCHAR(50) NULL,
  `enc_apellidoMaterno` VARCHAR(50) NULL,
  `enc_apellidoPaterno` VARCHAR(50) NULL,
  `enc_fkdepartamento` INT NULL,
  PRIMARY KEY (`enc_id`),
  INDEX `departamento_idx` (`enc_fkdepartamento` ASC) VISIBLE,
  CONSTRAINT `departamento`
    FOREIGN KEY (`enc_fkdepartamento`)
    REFERENCES `mydb`.`departamento` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_password` VARCHAR(10) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `aut_id` INT NOT NULL AUTO_INCREMENT,
  `aut_nombre` VARCHAR(50) NULL,
  `aut_apellidoMaterno` VARCHAR(50) NULL,
  `aut_apellidoPaterno` VARCHAR(50) NULL,
  `aut_semestre` INT NULL,
  `aut_correo` VARCHAR(50) NULL,
  `aut_fkcarrera` INT NULL,
  `aut_fktipo` INT NULL,
  `aut_fkdepartamento` INT NULL,
  `aut_fkencagardo` INT NULL,
  `aut_fkuser` INT NULL,
  PRIMARY KEY (`aut_id`),
  INDEX `carrera_idx` (`aut_fkcarrera` ASC) VISIBLE,
  INDEX `autorestipo_idx` (`aut_fktipo` ASC) VISIBLE,
  INDEX `departamento_idx` (`aut_fkdepartamento` ASC) VISIBLE,
  INDEX `encargado_idx` (`aut_fkencagardo` ASC) VISIBLE,
  INDEX `user_idx` (`aut_fkuser` ASC) VISIBLE,
  CONSTRAINT `carrera`
    FOREIGN KEY (`aut_fkcarrera`)
    REFERENCES `mydb`.`carrera` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `autorestipo`
    FOREIGN KEY (`aut_fktipo`)
    REFERENCES `mydb`.`autor_tipo` (`autt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `departamento`
    FOREIGN KEY (`aut_fkdepartamento`)
    REFERENCES `mydb`.`departamento` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `encargado`
    FOREIGN KEY (`aut_fkencagardo`)
    REFERENCES `mydb`.`encargado` (`enc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user`
    FOREIGN KEY (`aut_fkuser`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bitacora` (
  `bit_id` INT NOT NULL AUTO_INCREMENT,
  `bit_descripcion` TEXT NULL,
  `bit_fkrecurso` INT NULL,
  PRIMARY KEY (`bit_id`),
  INDEX `recursos_idx` (`bit_fkrecurso` ASC) VISIBLE,
  CONSTRAINT `recursos`
    FOREIGN KEY (`bit_fkrecurso`)
    REFERENCES `mydb`.`recurso` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor_recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor_recurso` (
  `autr_id` INT NOT NULL AUTO_INCREMENT,
  `autr_fkautor` INT NULL,
  `autr_fkrecurso` INT NULL,
  PRIMARY KEY (`autr_id`),
  INDEX `autor_idx` (`autr_fkautor` ASC) VISIBLE,
  INDEX `recurso_idx` (`autr_fkrecurso` ASC) VISIBLE,
  CONSTRAINT `autor`
    FOREIGN KEY (`autr_fkautor`)
    REFERENCES `mydb`.`autor` (`aut_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `recurso`
    FOREIGN KEY (`autr_fkrecurso`)
    REFERENCES `mydb`.`recurso` (`rec_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento_carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento_carrera` (
  `depc_id` INT NOT NULL AUTO_INCREMENT,
  `depc_fkdepartamento` INT NULL,
  `depc_fkcarrera` INT NULL,
  PRIMARY KEY (`depc_id`),
  INDEX `departamento_idx` (`depc_fkdepartamento` ASC) VISIBLE,
  INDEX `carrera_idx` (`depc_fkcarrera` ASC) VISIBLE,
  CONSTRAINT `departamento`
    FOREIGN KEY (`depc_fkdepartamento`)
    REFERENCES `mydb`.`departamento` (`dep_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carrera`
    FOREIGN KEY (`depc_fkcarrera`)
    REFERENCES `mydb`.`carrera` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
